ALTER TABLE coupons
  ADD COLUMN IF NOT EXISTS coupon_type VARCHAR(30) DEFAULT 'FLAT_DISCOUNT',
  ADD COLUMN IF NOT EXISTS max_discount_cap NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS discount_on VARCHAR(30) DEFAULT 'CART_TOTAL',
  ADD COLUMN IF NOT EXISTS applicable_categories JSONB DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS applicable_sku_ids JSONB DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS target_segment VARCHAR(30) DEFAULT 'ALL_USERS',
  ADD COLUMN IF NOT EXISTS target_user_ids JSONB DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS target_zones JSONB DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS is_first_order_only BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_stackable BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS exclude_sale_items BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS valid_days JSONB DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS valid_time_slots JSONB DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS payment_restriction VARCHAR(20) DEFAULT 'ALL',
  ADD COLUMN IF NOT EXISTS show_in_sections JSONB DEFAULT '["COUPON_LIST"]',
  ADD COLUMN IF NOT EXISTS priority_rank INT DEFAULT 10,
  ADD COLUMN IF NOT EXISTS banner_image_url TEXT,
  ADD COLUMN IF NOT EXISTS theme_color VARCHAR(10) DEFAULT '#2A7D4F',
  ADD COLUMN IF NOT EXISTS deep_link TEXT,
  ADD COLUMN IF NOT EXISTS terms_and_conditions TEXT,
  ADD COLUMN IF NOT EXISTS cashback_credit_trigger VARCHAR(30) DEFAULT 'ORDER_DELIVERED',
  ADD COLUMN IF NOT EXISTS cashback_expiry_days INT DEFAULT 14,
  ADD COLUMN IF NOT EXISTS tiers JSONB DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS bogo_min_qty INT DEFAULT 2;

CREATE TABLE IF NOT EXISTS coupon_redemptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  coupon_id UUID REFERENCES coupons(id),
  user_id UUID NOT NULL,
  order_id UUID NOT NULL,
  discount_applied NUMERIC(10,2) NOT NULL,
  redeemed_at TIMESTAMPTZ DEFAULT NOW()
);
