const mongoose = require('mongoose');
const userSchema = new mongoose.Schema(
  {
    phoneNumber: { type: String },
    email: { type: String, default: undefined },
    name: { type: String },
    phoneVerified: { type: Boolean, default: false },
    phoneVerifiedAt: { type: Date, default: null },
    onboardingCompleted: { type: Boolean, default: false },
    onboardingCompletedAt: { type: Date, default: null },
    acceptedTermsVersion: { type: String, default: null },
    acceptedTermsAt: { type: Date, default: null },
    acceptedPrivacyVersion: { type: String, default: null },
    acceptedPrivacyAt: { type: Date, default: null },
    passwordHash: { type: String, default: null },
    autoGeneratedPassword: { type: String, default: null },
    isPasswordAutoGenerated: { type: Boolean, default: false },
    passwordLastChangedAt: { type: Date, default: null },
    passwordLastChangedBy: { type: String, enum: ['system', 'user', 'admin', null], default: null },
    meta: { type: mongoose.Schema.Types.Mixed, default: {} },
    lastLogin: { type: Date, default: null },
    loginCount: { type: Number, default: 0 },
    status: { type: String, enum: ['active', 'inactive', 'blocked'], default: 'active' },
  },
  { timestamps: true }
);
userSchema.index({ onboardingCompleted: 1 });
userSchema.index({ phoneNumber: 1 }, { sparse: true });
userSchema.index({ email: 1 }, { unique: true, sparse: true, name: 'email_unique_sparse' });
userSchema.index({ status: 1 });
const CustomerUser = mongoose.models.CustomerUser || mongoose.model('CustomerUser', userSchema, 'customer_users');
module.exports = { CustomerUser };
