const mongoose = require('mongoose');
const userSchema = new mongoose.Schema(
  {
    phoneNumber: { type: String },
    email: { type: String, default: undefined },
    name: { type: String },
    /** Public URL of the customer's profile photo (S3). */
    avatarUrl: { type: String, default: '' },
    phoneVerified: { type: Boolean, default: false },
    phoneVerifiedAt: { type: Date, default: null },
    onboardingCompleted: { type: Boolean, default: false },
    onboardingCompletedAt: { type: Date, default: null },
    acceptedTermsVersion: { type: String, default: null },
    acceptedTermsAt: { type: Date, default: null },
    acceptedPrivacyVersion: { type: String, default: null },
    acceptedPrivacyAt: { type: Date, default: null },
    passwordHash: { type: String, default: null },
    autoGeneratedPassword: { type: String, default: null },
    isPasswordAutoGenerated: { type: Boolean, default: false },
    passwordLastChangedAt: { type: Date, default: null },
    passwordLastChangedBy: { type: String, enum: ['system', 'user', 'admin', null], default: null },
    meta: { type: mongoose.Schema.Types.Mixed, default: {} },
    lastLogin: { type: Date, default: null },
    loginCount: { type: Number, default: 0 },
    status: { type: String, enum: ['active', 'inactive', 'blocked'], default: 'active' },
    /** Optional billing / payment contact saved from checkout for reuse */
    savedCheckoutContact: {
      fullName: { type: String, default: undefined },
      email: { type: String, default: undefined },
      phone: { type: String, default: undefined },
    },
    /** Communication channel preferences for the customer app / web */
    notificationPreferences: {
      /** Device / Expo / Web push alerts (OS / browser tray) */
      push: { type: Boolean, default: true },
      /** In-app Notification Center / bell badge */
      inApp: { type: Boolean, default: true },
      sms: { type: Boolean, default: true },
      whatsapp: { type: Boolean, default: true },
      email: { type: Boolean, default: true },
      dnd: { type: Boolean, default: false },
      /** Local quiet hours when DND is on (0–23). */
      dndStartHour: { type: Number, default: 22 },
      dndEndHour: { type: Number, default: 7 },
      /**
       * Per-category channel matrix:
       * { order: { push, inApp, sms, whatsapp, email }, offers: {...}, ... }
       */
      categories: { type: mongoose.Schema.Types.Mixed, default: undefined },
    },
  },
  { timestamps: true }
);
userSchema.index({ onboardingCompleted: 1 });
userSchema.index({ phoneNumber: 1 }, { sparse: true });
userSchema.index({ email: 1 }, { unique: true, sparse: true, name: 'email_unique_sparse' });
userSchema.index({ status: 1 });
const CustomerUser = mongoose.models.CustomerUser || mongoose.model('CustomerUser', userSchema, 'customer_users');
module.exports = { CustomerUser };
